### ISSUE TITLE
RACKit RQuest API Client

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/hutch-relay#11]
# Summary

This is a reasonably high-level issue for tracking initial ("v1") work on an "RQuest API Client" area within RACKit.

# Tasks

- [x] Health-Informatics-UoN/hutch-cohort-discovery#43
- [x] Health-Informatics-UoN/hutch-cohort-discovery#44
- [x] Health-Informatics-UoN/hutch-cohort-discovery#45
- [ ] Health-Informatics-UoN/hutch-relay#8
- [ ] Documentation
    - hopefully this is mostly covered by the above tracked items, but there might be some higher level docs around the complete feature piece.

# Acceptance Criteria

- [ ] All task issues above are closed
- [ ] Satisfactory high level documentation - TBD?
    - Where? Website specifically for RACKit? Part of Hutch
    - What? API reference? usage of library in general (maybe too soon for this issue to pick up?
