### ISSUE TITLE
Publish packages to Nuget.org

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/hutch-relay#7]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Versioned releases of the library should be published to Nuget.org

### Acceptance Criteria

- [ ] GitHub release workflow pushes a matching versioned package to nuget.org
- [ ] Documentation added.

### Tasks

- [ ] Add Nuget API key to Repository secrets.
- [ ] Amend Github Release workflow to build a nuget package and publish to it to nuget.org
- [ ] Documentation.

### Confirm creation

- [x] This issue is ready
