### ISSUE TITLE
Submitting Results for a Collection's Distribution query job

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/hutch-relay#8]
## Acceptance Criteria

- [ ] RACKit API client can successfully upload result files
- [ ] RACKit API client can successfully send results referencing results files to the target (Rquest) API
- [ ] This should work for Distribution queries
- [ ] Error logging for when a request fails. 
- [ ] Unit tests pass
- [ ] Sample application shows sending results
- [ ] Documentation in .md

## Tasks

- [ ] Add the results file method
- [ ] Write tests
- [ ] Write error handling in method
- [ ] Update sample application
- [ ] Integration test via sample application
- [ ] Update documentation

**Comment by beforan** [comment]
This issue formerly conflated some functionality (separate Results upload vs Distribution query support).

Following better understanding this now represents the (lower priority) separate results upload work, and will be refined further in future.

The Distribution Query specific aspects (moving to support Generic Code and Demographics queries) are now tracked here #43
